### ISSUE TITLE
Error in cmd make -j -f Vour.mk Vour__ALL.a

### ISSUE THREAD

**Issue by Sangs19** [verilator/verilator#2178]
![Screenshot from 2020-02-25 18-19-53](https://user-images.githubusercontent.com/61424583/75249108-92d40e00-57fb-11ea-942e-f4c7e1ce8890.png)

**Comment by wsnyder** [comment]
Looks like your $SYSTEMC variable isn't pointing at the SYSTEMC kit but rather an include file.  Check all your environment variables point to the right thing.

BTW for the future when possible please insert text rather than an image, as text allows cut & paste and the search engines to properly index it.

**Comment by Sangs19** [comment]
> ![Screenshot from 2020-02-25 18-19-53](https://user-images.githubusercontent.com/61424583/75249108-92d40e00-57fb-11ea-942e-f4c7e1ce8890.png)

Thanks. Cleared above error but the next command is not giving output from the manual.

make -j -f Vour.mk ../sc_main.o verilated.o 

is giving a statement of 

make: no rule to make target '../sc_main.o'

**Comment by wsnyder** [comment]
You can't put a path on make targets, just use sc_main.o
