### ISSUE TITLE
Assignment in a loop

### ISSUE THREAD

**Issue by cooledit98** [verilator/verilator#2509]
I have a simple assignment in a loop, like:

reg [3:0] reg_id [153:0];
reg [3:0] id_delay;
integer i;
always @(posedge clk)
     if (valid)
         for (i=0; i<=153; i=i+1)
              begin
                    reg_id[i] <= id_delay;
              end

But verilator reported errors:
Unsupported: Delayed assignment to array inside for loops.

How to solve this issue?
Why verilator can't support assignment in loop.

**Comment by wsnyder** [comment]
Using "--unroll-count 256" should get around this.

Basically it complains because writing this loop is going to expand to 152 statements that need to execute each and every statement.  If you're writing for an ASIC, then you'd be better off for both Verilator and real design power using a FIFO with write and read pointer.
