### ISSUE TITLE
Please only build and install _dbg executables conditional on a configuration option

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#2528]
Currently the FreeBSD port always builds bin/verilator_bin_dbg and bin/verilator_coverage_bin_dbg and then deletes them. This wastes CPU time.

Could you please add a config option that controls this?

Thanks,
Yuri

**Comment by wsnyder** [comment]
Looked at this, but this would require also reworking the install and other items, and for the small CPU gain only at build time does not seem worth the maintenance cost (esp as debug builds faster than optimized).   I would also encourage you to still build the debug version so that "--debug" works properly.

So thanks for reporting but at this time I'd prefer not to do this.
