### ISSUE TITLE
The --hierarchical option causes failure with "--make gmake" option: Unsupported: unpacked arrays with protect-lib on 'val'

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#2558]
```
%Error-UNSUPPORTED: x.v:36:16: Unsupported: unpacked arrays with protect-lib on 'val'
   36 | input[31:0]  val[5:0];
      |              ^~~~~~
```

This failure doesn't happen without the ```--hierarchical``` option, and also with the ```--hierarchical``` option with ```--make cmake```.

**Comment by yTakatsukasa** [comment]
Hierarchical verilation does not support unpacked array ports because protect-lib, which is an underlying mechanism, does not support it yet.
Protect-lib does not support unpacked array ports because Verilator does not support unpacked array in DPI-C import/export yet..

Supporting unpacked array on DPI-C is filed in #2508 .
