### ISSUE TITLE
Systemc Example not running

### ISSUE THREAD

**Issue by rahulraveendran15-coder** [verilator/verilator#2663]
How may we help - what is your question?
I have tried using systemc with verilator and it complains the below error:
![image](https://user-images.githubusercontent.com/60182727/100906952-0bbe6f80-34ca-11eb-90e9-d9a18a9f4aca.png)

I am using systemc version 2.3.3 from accelera website. My system is centos 7 64 bit

At the same time when I tried systemc 2.3.0 its running fine.

**Comment by wsnyder** [comment]
This is likely not directly related to Verilator, something looks wrong in your SystemC installation, try SystemC's examples, and look at if the headers match the link libraries being used.  Report back if you could to help who gets it next.  (BTW nicer to put in the text of the error rather than a picture so it's searchable and easier to read.)

**Comment by wsnyder** [comment]
Feel free to reopen if it is really something Verilator related, and also please do report back what was the problem if you can, thanks.
