### ISSUE TITLE
How to limit the number of threads used by make

### ISSUE THREAD

**Issue by sjalloq** [verilator/verilator#2762]
I'm running Verilator via fusesoc and noticed that it seems to be using all available CPUs on my system.  I've tried to limit it to 4 but with no luck.  From the documentation I thought the relevant options was `-MAKEFLAGS "-j4"` but that hasn't worked. 

The full command that is executed is `verilator -f tigris_ip_top_verilator_0.1.vc -MAKEFLAGS "-j4" --trace --trace-fst --trace-structs --trace-params --trace-max-array 1024 -CFLAGS "-std=c++11 -Wall -DVM_TRACE_FMT_FST -DVL_USER_STOP -DTOPLEVEL_NAME=digitalsubsystem_top_verilator -g" -LDFLAGS "-pthread -lutil -lelf" -Wall --threads 4 -Wno-fatal`

what magic option am I staring at but can't see?

**Comment by wsnyder** [comment]
MAKEFLAGS is only used with --build.  As that verilator command as it doesn't have --build, verilator should only be using one CPU.  However the following "make" which you didn't show the command line for is probably using "-j". Or you have some higher-level make calling that make, which is using "-j" instead of "-j4".
