### ISSUE TITLE
Dollar signs in file name are not escaped in generated cpp model and makefile

### ISSUE THREAD

**Issue by MasterBabol** [verilator/verilator#2768]
Verilator works well even though a module file name contains a dollar sign; However, the generated Cpp model and makefile also contain the dollar sign, so model build process fails.

![image](https://user-images.githubusercontent.com/17945273/105795010-7a521200-5fcf-11eb-8b82-b30e6ba1c829.png)

![image](https://user-images.githubusercontent.com/17945273/105795433-2d227000-5fd0-11eb-98fa-82e0bfe52d79.png)

![image](https://user-images.githubusercontent.com/17945273/105795492-49261180-5fd0-11eb-8f2f-f425c6aaa03d.png)

**Comment by wsnyder** [comment]
As dollar signs identify shell and makefile variables I would very strongly encourage you/your organization to adopt a naming strategy that matches C identifiers (letter, then number or letters or _), as doubtless other problems will arise in Verilator and other tools.

However was simple enough to fix this particular issue, so fixed.

P.S. Please in the future try to paste text rather than images, thanks.
