### ISSUE TITLE
Could you please advise stable verilator version for G++8.4 or G++9.3 or G++ 7.4?

### ISSUE THREAD

**Issue by NazerkeT** [verilator/verilator#3004]
Good Day,
Could you please advise a stable Verilator version for `G++8.4` or `G++9.3` or `G++ 7.4` for Ubuntu 18.04 machine? I was trying to run a Ariane core with Verilator v4.014, v4.034, v4.100 and v4.102, however all of them have failed with respective gcc and g++ compiler versions. Would be happy for some advice on this matter.

Thanks,
Best wishes

**Comment by wsnyder** [comment]
Verilator is regressed using Ubuntu 16.04 (but will soon be end-of-life), 18.04 (since Verilator 3.922) and 20.04 (since Verilator 4.032).

As to the GCC versions for those, see https://distrowatch.com/table.php?distribution=ubuntu

It might be more productive to instead indicate what the failure error was and we can help debug that.
