### ISSUE TITLE
Re-initialize instance of verilated SystemC module without destroying it

### ISSUE THREAD

**Issue by wltr** [verilator/verilator#3015]
Hi,

Is there a way to reset/reinitialize a verilated model without destroying an instance and recreating it? I'm using SystemC and as you're aware, the simulation context doesn't support dynamic allocation of modules once the simulation has started (i.e. after the first run). So having a single instance that can be reinitialized with different values of randReset would be tremendously helpful for my unit tests. 

Thanks,
Johannes

**Comment by stephenry** [comment]
I recently worked with a team that was attempting to do something similar for a large SOC simulation environment, although not with Verilator. The options are:

- Create a single model whose lifetime exists through the entirety of the test and is (somehow) re-initialized between unit tests. This isn't typically done in practise and is fraught with problems (assuming that it could be made to work at all).
- Place individual unit tests into separate executables so that the model does not need to be reconstructed post SystemC elaboration/initialisation. An easy fix typically; your verif. flow looks more like a standard ASIC/FPGA regression environment, than a software test environment.
- Subvert SystemC by reloading libsystemc whenever starting a unit test. This can be done using dlmopen, and I've seen it work, but not necessarily something I would advise (but then I wouldn't personally advise using SystemC for anything).
- Drop SystemC altogether and instead emit C++ from Verilator. I do this for my side projects and it works well within a Google Test/CTest regression environment (https://github.com/stephenry/m/blob/master/tb/tests/regress.cc). The recent "Context" additions to Verilator help this somewhat, but I never really encountered any issues in their absence. Requires moderate knowledge of C++, but most (if not all) of the features that you gain from SystemC can be rewritten as necessary.
