### ISSUE TITLE
Fix internal fault on mix of edge and combo always

### ISSUE THREAD

**Issue by jsmith173** [verilator/verilator#3170]
Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)
Files attached. Tested on MSYS64.
I have some other working example on MSYS64.

What 'verilator --version' are you using?  Did you try it with the git master version?
4.213

Would you be willing to try to fix Verilator yourself with assistance?
Yes

[v_app.zip](https://github.com/verilator/verilator/files/7335898/v_app.zip)

**Comment by wsnyder** [comment]
Fixed so this code now gives an internal error rather than aborting.

     %Error: Internal Error: v_app1.v:13:26: ../V3Clock.cpp:139: No clock found on sense item
       13 |    always @(posedge C or PRE or CLR)

Basically you should have had 'always @ (posedge C or negedge PRE or negedge CLR).

Ideally this would be supported and work the right way.

Less ideally it should give a clearer warning this is not supported.

Both are exercises for the future, if you'd like to make a patch for a clearer warning this would be welcome.

**Comment by wsnyder** [comment]
This is fixed on the develop-v5 branch towards 5.000.
