### ISSUE TITLE
Better alternative to vcddiff

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3428]
vcddiff has a couple of annoying issues:
- Arbitrary limits on signal sizes due to use of static buffers
- Cannot cope with some non-trivially different but isomorphic VCD files. My fix to this is to feed both inptus through vcd2fst then fst2vcd, which then often confirms the  files are indeed identical

Rather than trying to fix these, it should not be hard to write write a python alternative that is good enough for the limited size traces used in the test-suite. we need to assert that:
- The signal declarations (header) are isomorphic
- At each time point in the files, the values are identical

None of these sound particularly hard.

**Comment by wsnyder** [comment]
If your only temporary blocking issue is size, it's easy enough to update the vcddiff code that we use to hardcode something larger.

If doing the work personally I would be afraid this is one of those problems that seems easy but proves much harder in the details.   Also someone else will use it and I'd get stuck supporting it - I can rightly claim that vcddiff is not something I'm supporting.  Although as it turns out the parser inside VCDDIFF was ripped out of my Dinotrace by another author, without my knowing, which is fine, so it's not like I had zero impact on it ;).

Anyhow if you want to do the work have fun and I'm glad to remove the ugly vcddiff dependency.

**Comment by gezalore** [comment]
> VCDDIFF was ripped out of my Dinotrace by another author, without my knowing, which is fine, so it's not like I had zero impact on it ;).

Ah, your static variables again :P

Regarding supporting its use by other: I don't think that's a problem, its an internal tool, so we are not responsible for supporting it beyond our own needs.

I have a patch parked because of this, that emits strings into a VCD file for profiling, which can be arbitrarily large, which is what mostly motivated this issue. I will look into it when I want to commit that, feel free to ignore otherwise.

**Comment by wsnyder** [comment]
Ok.  Dinotrace was written before there were strings, but signals were dynamic allocated ;)

**Comment by wsnyder** [comment]
Closing as this isn't something we have to do, but welcome a new improved vcddiff if it comes!
