### ISSUE TITLE
 ./t/t_timing_protect.pl is non-deterministic

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3717]
Keep rerunning `./t/t_timing_protect.pl --no-skip-identical` and should observe the hashes change, probably something depends on a memory address. 

@kbieganski could you take a look?

**Comment by wsnyder** [comment]
BTW don't try with debug as it might (I didn't check) be stable because we turn off address randomization.

**Comment by kbieganski** [comment]
:( I'll look at it next week.

**Comment by wsnyder** [comment]
Looking at the command line it just isn't setting a stable key, so by design it is random.  I'll add it shortly.

**Comment by kbieganski** [comment]
Oh, okay. I was confused because I removed everything from the test module and it was still nondeterministic. Thanks, I'm not familiar with how the protect stuff works.

**Comment by gezalore** [comment]
> Oh, okay. I was confused because I removed everything from the test module and it was still nondeterministic. Thanks, I'm not familiar with how the protect stuff works.

Nor am I apparently, should have been able to figure that one out :)

**Comment by wsnyder** [comment]
protect encrypts the signal/file names using a key.  By default the key is picked at runtime from a true-random source, it can't be hardcoded to any computable algorithm, otherwise anyone with sources could run a dictionary attack to decrypt the signal names.  So all tests should always be giving a --protect-key that is constant.
