### ISSUE TITLE
internals documentation not generated properly

### ISSUE THREAD

**Issue by gkamendje73** [verilator/verilator#3747]
Thanks for taking the time to report this.

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)
The following link that points to the documentation of the `internals` is broken. 
https://veripool.org/guide/latest/internals.rst

The `internals` documentation is not generated either when running `make docs`. I do not get any error warning/error on this. (PDF documentation fails to build because of missing `*.sty` Latex files but that is another story)

What 'verilator --version' are you using?  Did you try it with the git master version?
Latest (true on the latest website as well)
What OS and distribution are you using?
Centos 7
May we assist you in trying to fix this in Verilator yourself?
Yes

**Comment by wsnyder** [comment]
The assumption, perhaps incorrect, was people would be unlikely to look at a PDF of internals since it is intended for developers that can read the source, or alternatively look at https://github.com/verilator/verilator/blob/master/docs/internals.rst

The veripool link should be fixed to redirect to github.

**Comment by wsnyder** [comment]
Assuming above answers, if you think we need more feel free to comment/reopen, thanks.

**Comment by gkamendje73** [comment]
Thanks for the fix. Reading the internal docu in an web browser is way easier.
