### ISSUE TITLE
Dfg cppcheck conjunction warning

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#3771]
@gezalore running cppcheck complains correctly I believe about this, and I'm not sure what you intended.

src/V3DfgPeephole.cpp:1513: Logical disjunction always evaluates to true:

                   && (!elsep->hasMultipleSinks() || elsep->hasMultipleSinks())) {

**Comment by gezalore** [comment]
The intention with these checks is to only apply the transformation if the intermediate terms become redundant and hence can be eliminated (otherwise we need both the original and new expressions, which ends up being more work than the original). What I typed there though is high nonsense, will fix shortly.
