### ISSUE TITLE
CONTRIBUTING links to https://verilator.org/forum, which is forwarded to the Issues page, but Discussions could be enabled for repo

### ISSUE THREAD

**Issue by tudortimi** [verilator/verilator#4167]
It would be possible to enable the Discussions page, to provide a forum and keep Issues focused on bug reports and feature requests. https://verilator.org/forum could then link to that.

**Comment by wsnyder** [comment]
For the current time, I prefer to stick with discussions as issues, because it saves people of thinking "is this a forum or issue", because discussions often are describing problems that need issues, and as it is with issues to make sure that questions etc are not forgotten to be answered.

(Note 3-4 years ago there were Verilator forums)
