### ISSUE TITLE
Easy Assignment to Vector and Struct in Verilated Model of C++ testbench

### ISSUE THREAD

**Issue by Xlucidator** [verilator/verilator#4361]
if I want to test a model like：
```systemverilog
typedef struct packed {
    logic conponent_a;
    logic [31:0] component_b;
    // so on ...
} b_struct_t;

module A (
    input logic [4:0] a_vector,
    input b_struct_t b_struct,
    input b_struct_t [1:0] c_mixed
);
    // ...
endmodule
```
How can I write its C++ testbench easily for this kind of module? 

Currently I could not assign the input correctly with `top->b_struct = ...`. Maybe I could manage it by manipulate C++ struct / vector in level of 'bit', but that's indeed tedious and difficult.

Wish verilator can improve Verilated Model or something for this and I would be really grateful! ( Or what can I do for this?)

**Comment by wsnyder** [comment]
packed structs are necessarily flattened at the model header interface to C++.  As to making a C++ abstraction that you could then use to decode/encode the packed struct that feature is requested in #860. Unfortunately that bug is fairly old, so it's indicative that it will likely not be fixed soon, unless you would like to work on it - if so please comment in that bug, thanks!

**Comment by Sustrak** [comment]
Hi @Xlucidator, maybe you can try [this tool](https://github.com/MikePopoloski/slang/tree/master/tools/reflect) I wrote recently which does what I think you are looking for.
