### ISSUE TITLE
How to debug a verilator simulation fail that passes with --trace

### ISSUE THREAD

**Issue by VarunKoyyalagunta** [verilator/verilator#4408]
We are using verilator on a fairly large design. We've been wanting to upgrade to verilator 5. However we noticed there are some simulation fails that are present in verilator 5 that are not in verilator 4. Further, adding --trace makes verilator 5 pass the test. I'm guessing this is a verilator 5 functional bug. 

I was wondering if there's a recommended process for debugging fails like this. My first thought is to use gdb to try to figure out where in the design something is being mis-simulated, but due to our design complexity this is not the most straightforward task. Are there other techniques users would recommend when running into problems like this to help debug?

**Comment by wsnyder** [comment]
It's likely a bug; turning on tracing disables some optimizations and indirectly changes inlining and other decisions. Some possible approaches:

1. turn on trace only to depth 1 (top level signals), and see if that works.  If it does, try level 2, etc. This should allow visibility of some signals perhaps enough to debug.
2. turn on trace globally then using a .vlt file, turn off trace on files one-by-one until you identify the relevant file.  Then you can similarly turn off trace on a signal-by-signal basis.  The hope is to get to the signal of interest that breaks it.  Also this approach should allow visibility of some signals.
3. dump state in the broken model at appropriate points using $display until you find the signal that is broken.  (i.e. debug without using trace)
4. run both v4 and v5 code in parallel, and compare signals that are common between them to find a mismatch.  The verilator libraries aren't designed to run two versions in the same process, so you'd need to have two processes with shared memory or a socket or otherwise between them.  Alternatively you'd need to edit one of the verilated libraries to change the name of the symbols to remove the conflict.

Closing as answered but feel free to follow up.
