### ISSUE TITLE
Not able to write to ARM generated memory whereas same model and TB is working with iverilog

### ISSUE THREAD

**Issue by mano009** [verilator/verilator#5654]
```
`timescale Ins/ Ips
module mem 128x32 (Q, CLK, REN, WEN, A, D, SPD_md)

parameter ADDR WIDTH = 7;
parameter DATA WIDTH = 32;

input [DATA WIDTH-1:0] D;
input [ADDR WIDTH-1:0] A;
input CLK;
input REN, WEN;
input SPD_md
output [DATA WIDTH-1:0] Q,

wire CENA_w, WENA_w, CENB_w, WENB_w;

wire [2:0] EMA_w;

assign CENA_w = WEN ? 1'b1:1'b0;
assign WENA_w = WEN ? 1'b1:1'b0;
assign CENB_w = REN ? 1'b1:1'b0;
assign WENB_w = 1'b1;
assign EMA_w = SPD_md ? 3'b100:3'b111;

sram_dp_128x32 mem_inst
(.CENYA(), .WENYA(), .AYA(), . CENYB(), .WENYB(), .AYB(),.QA(),.QB(Q),
. SOA(),.SOB(),.CLKA(CLK) ,.CENA(CENA_w) ,.WENA(WENA w) , .AA(A),.DA(D) ,.CLKB(CLK) 
.CENB(CENB_w) , .WENB(WENB_w) , .AB(A),. DB(128'd0),. EMAA(EMA_w) ,
. EMAWA(2'b10), . EMASA(1'b0),. EMAB(EMA_w) ,.EMAWB(2'b10), .EMASB(1'b0), .TENA(1'b1),.TCENA(1'b1),
 . TWENA(1'b1),  .TAA(8'b0),.TDA(32'b0),.TENB(1'b1), .TCENB(1'b1),.CRE2(1'b0), . FCA1(6'b0),. FCA2(6'b0),
.COLLDISN(1'b1), .WABL(1'b1), .WABLM(2'b11));
 
endmodule

```

Attached code is the wrapper for my ARM real memory. Tried to simulate with my below TB. While reading I am not able to read.

verilator run command: 
veritator --binary --sv --exe sram_tb.v mem 128x32.v sram_dp_128x32.v -Wno-fatal -trace-fst +define+ARM_DISABLE_EMA_CHECK

Verilator 5.928 2024-08-21

OS - vnc

May we assist you in trying to fix this in Verilator yourself? - yes

(Please avoid attaching screenshots that show text - you can convert images to text using e.g. https://ocr.space)

**Comment by wsnyder** [comment]
There's no attachment. But please don't post any material you don't have rights to post, especially if it's under an Arm NDA.

Usually if there's a difference Verilator gave a warning message of some sort.  Otherwise look at waves and compare the models and trace it back to why, then make that into some very small example you can post showing only that little piece of code, and how the results are different, and we'll comment.  Closing in meantime.
